### ISSUE TITLE
 Prepare a platform for technical information

### ISSUE THREAD

**Issue by kazu80** [dev-protocol/community#17]
Prepare a platform for sharing technical information. 
Request, articles can be managed on Github.
I think [11ty](https://www.11ty.dev/) is best way. And we want it be like [web.dev](https://web.dev/).

`web.dev`'s repo. I will check later
https://github.com/GoogleChrome/web.dev

**Comment by defi-er** [comment]
Here's some crypto examples of documentation. It seems as if all examples use the same template for their documentation. Here's Dev Protocol's [docs](docs.devprotocol.xyz) that discusses the core protocol. I would prefer if Dev Protocol had one documentation that discusses A-Z (Protocol to Integrations). This makes sense because a learning phase it from A-Z and doesn't start and end at Z (Just Integrations). 

**Examples**
[Chainlink](https://docs.chain.link/docs/running-a-chainlink-node) 
[Synthetix](https://docs.synthetix.io)
[Aave](https://docs.aave.com/developers/)

**Websites Used**
Dev Protocol docs currently uses Gitbook
Chainlink and Aave also use Gitbook
Synthetix uses [MkDocs](https://www.mkdocs.org) & [Material for MkDocs](https://squidfunk.github.io/mkdocs-material/)

**Documentation Format**

1. Welcome
2. Protocol
3. Tokens
4. Contract List
5. Integrations
6. Use Cases
7. Libraries
8. Smart Contract Architecture

**Comment by aggre** [comment]
We need both documentation for covers all specifications and documentation for provides user-friendly cross-cutting information about specific topics. That is tuned according to the target audience's knowledge level and clearly shows the technical topics that should be cleared in advance. I think it's essential not to understand the specifications but to give the best answer for the purpose.

Gitbook is the perfect tool for "documentation for covers all specifications." I understand that @kazu80 is looking for the latter tool.

**Comment by aggre** [comment]
> I think 11ty is best way. And we want it be like web.dev.

@kazu80 I agree with 11ty!

**Comment by kazu80** [comment]
Thank you for sharing @defi-er .

As from @aggre , I want this to be a topic rather than a manual. This is Like a blog. I imagine that the engineers will be interested in DEV after reading this article, and then read the manual and use DEV.
